### ISSUE TITLE
basic test not working

### ISSUE THREAD

**Issue by atlante77** [gpocentek/python-gitlab#103]
Hello,

I try to test gitlab on my debian jessie with python 2.7 but i have an issue : 
```
import gitlab

# private token authentication
gl = gitlab.Gitlab('http://gitlab.toto.net', 'totototototototo')
gl.auth()

# list all the projects
projects = gl.projects.list()
for project in projects:
    print(project)

```

Error : 
`Traceback (most recent call last):
  File "test.py", line 5, in <module>
    gl.auth()
  File "/usr/local/lib/python2.7/dist-packages/gitlab/__init__.py", line 184, in auth
    self.token_auth()
  File "/usr/local/lib/python2.7/dist-packages/gitlab/__init__.py", line 204, in token_auth
    self.user = CurrentUser(self)
  File "/usr/local/lib/python2.7/dist-packages/gitlab/objects.py", line 389, in __init__
    data = self.gitlab.get(self.__class__, data, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/gitlab/__init__.py", line 422, in get
    return r.json()
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 808, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
`

And without auth() : 
`Traceback (most recent call last):
  File "test.py", line 8, in <module>
    projects = gl.projects.list()
  File "/usr/local/lib/python2.7/dist-packages/gitlab/objects.py", line 121, in list
    return self.obj_cls.list(self.gitlab, **args)
  File "/usr/local/lib/python2.7/dist-packages/gitlab/objects.py", line 261, in list
    return gl.list(cls, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/gitlab/__init__.py", line 370, in list
    results = [cls(self, item, **cls_kwargs) for item in r.json()
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 808, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
`

Thanks in advance.

**Comment by gpocentek** [comment]
Hello,

Are you sure that you're using the correct URL. Maybe it's https://, not http://

There's no easy way to debug this kind of problem for the moment, this is something I'd have to work on.

**Comment by gpocentek** [comment]
Please re-open if this is still an issue.
