### ISSUE TITLE
Cant save issue

### ISSUE THREAD

**Issue by kennedyshead** [gpocentek/python-gitlab#152]
```
        issue = self.gl.issues.get(issue_id)      
        issue.state_event = "close"           
        issue.save() 
```

Gives me             

```
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/Users/***/git/***/app/services.py", line 98, in run
    self.process_queue()
  File "/Users/***/git/***/app/services.py", line 105, in process_queue
    item[0][0](item[0][1], item[1])
  File "/Users/***/git/***/app/services.py", line 310, in close_issue
    issue.save()
  File "/usr/local/lib/python2.7/site-packages/gitlab/objects.py", line 320, in save
    self._update(**kwargs)
  File "/usr/local/lib/python2.7/site-packages/gitlab/objects.py", line 313, in _update
    raise NotImplementedError
NotImplementedError
```

**Comment by gpocentek** [comment]
Hi,

Issues retrieved using ``gl.issues.list()`` are not editable. You need to retrieve project-related issues: ``gl.project_issues.get(issue_id, project_id=your_project_id)``.

This is something I can probably improve but for now there's no other solution.

**Comment by kennedyshead** [comment]
Thank you, that sorted my issue. And thank you for your effort with this code!

**Comment by gpocentek** [comment]
I've been thinking about this issue, and I'm not sure that what I intended to do is a good solution (make the Issue objects writable). There's a solution to edit issues so no need to make the python API behave differently from the upstream API.
