### ISSUE TITLE
Problem creating hook

### ISSUE THREAD

**Issue by kennedyshead** [gpocentek/python-gitlab#162]
The call is accepted and the hook exists

```
Traceback (most recent call last):

  File "/Users/magnusknutas/git/thefarm/kivy/env/lib/python3.5/site-packages/gitlab/objects.py", line 142, in create
    return self.obj_cls.create(self.gitlab, data, **args)
  File "/Users/magnusknutas/git/thefarm/kivy/env/lib/python3.5/site-packages/gitlab/objects.py", line 352, in create
    obj.save()
  File "/Users/magnusknutas/git/thefarm/kivy/env/lib/python3.5/site-packages/gitlab/objects.py", line 322, in save
    self._create(**kwargs)
  File "/Users/magnusknutas/git/thefarm/kivy/env/lib/python3.5/site-packages/gitlab/objects.py", line 307, in _create
    json = self.gitlab.create(self, **kwargs)
  File "/Users/magnusknutas/git/thefarm/kivy/env/lib/python3.5/site-packages/gitlab/__init__.py", line 585, in create
    raise_error_from_response(r, GitlabCreateError, 201)
  File "/Users/magnusknutas/git/thefarm/kivy/env/lib/python3.5/site-packages/gitlab/exceptions.py", line 168, in raise_error_from_response
    response_body=response.content)
gitlab.exceptions.GitlabCreateError: 200: b'[]'
```

**Comment by gpocentek** [comment]
Could you provide a code sample so I can try to reproduce? Thanks.

**Comment by kennedyshead** [comment]
```
        project = self.gl.projects.get(project_id)
        hooks = project.hooks.list()
        should_create = True

        for hook in hooks:
            if hook.url == '*' and should_create:
                should_create = False
            elif hook.url == '*':
                hook.delete()

        if should_create:
            project.hooks.create(
                {
                    'url': '*',
                    'push_events': False,
                    'issues_events': True,
                    'note_events': True,
                    'merge_requests_events': True,
                    'tag_push_events': False,
                    'build_events': True
                }
            )

**Comment by kennedyshead** [comment]
In python 2.7 it works, python 3.5 is not working (if I did not miss anything else)

**Comment by kennedyshead** [comment]
Actually this goes for both updates and deletes as well in py 3.5

**Comment by gpocentek** [comment]
I have not been able to reproduce the problem, both with python 2.7 and 3.5:
`````python
Python 3.5.2+ (default, Sep 22 2016, 12:18:14) 
[GCC 6.2.0 20160927] on linux
...
>>> p.hooks.create({'url': 'http://foo.bar.com', 'push_events': False, 'issues_events': True, 'note_events': True, 'merge_requests_events': True, 'tag_push_events': False, 'build_events': True})
<gitlab.objects.ProjectHook object at 0x7fb4a55c9208>
>>> h = p.hooks.list()[0]
>>> h.push_events = True
>>> h.save()
>>> h = p.hooks.list()[0]
>>> h.push_events
True
>>> h.delete()
True
`````

**Comment by gpocentek** [comment]
Could you test with the master branch? Thank you.

**Comment by kennedyshead** [comment]
It would seem that this was a gitlab issue, now this work as intended. Thank you for support!
