### ISSUE TITLE
Connection error when the latest requests is installed

### ISSUE THREAD

**Issue by voidpp** [gpocentek/python-gitlab#189]
I get this error when try to authenticate to gitlab:
```
Traceback (most recent call last):
  File "t.py", line 6, in <module>
    gl.auth()
  File "/usr/local/lib/python2.7/dist-packages/gitlab/__init__.py", line 244, in auth
    self.token_auth()
  File "/usr/local/lib/python2.7/dist-packages/gitlab/__init__.py", line 264, in token_auth
    self.user = CurrentUser(self)
  File "/usr/local/lib/python2.7/dist-packages/gitlab/objects.py", line 377, in __init__
    data = self.gitlab.get(self.__class__, data, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/gitlab/__init__.py", line 497, in get
    r = self._raw_get(url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/gitlab/__init__.py", line 360, in _raw_get
    "Can't connect to GitLab server (%s)" % e)
gitlab.exceptions.GitlabConnectionError: Can't connect to GitLab server (sequence item 0: expected string, NoneType found)

```
Content of t.py:
```py

import gitlab

gl = gitlab.Gitlab(u'http://10.14.100.15', u'2jEsFApRnA9hszKhSaYx')

gl.auth()
```

When try to run this code with `request@2.8.1` it is works well, but when I try with the latest (2.12.3) this error occurred.

**Comment by gpocentek** [comment]
Should be fixed in the master: https://github.com/gpocentek/python-gitlab/issues/188
