### ISSUE TITLE
Error Gitlab auth() : Object doesn't exist

### ISSUE THREAD

**Issue by marcolefo** [gpocentek/python-gitlab#19]
Hello
Now, I can't auth :

```shell
Python 2.7.3 (default, Jan  2 2013, 13:56:14) 
[GCC 4.7.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import gitlab
>>> gl=gitlab.Gitlab('http://gitlab.domain','admin_token')
>>> gl
<gitlab.Gitlab object at 0x1e91310>
>>> gl.auth()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/gitlab.py", line 100, in auth
    self.token_auth()
  File "/usr/local/lib/python2.7/dist-packages/gitlab.py", line 118, in token_auth
    self.user = CurrentUser(self)
  File "/usr/local/lib/python2.7/dist-packages/gitlab.py", line 541, in __init__
    data = self.gitlab.get(self.__class__, data, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/gitlab.py", line 244, in get
    raise GitlabGetError("Object doesn't exist")
gitlab.GitlabGetError: Object doesn't exist
```

**Comment by gpocentek** [comment]
The GitlabGetError raised also returns the error code and message from the remote web server, so the error should be a bit clearer.
