### ISSUE TITLE
sudo not woks with latest gitlab

### ISSUE THREAD

**Issue by Delagen** [gpocentek/python-gitlab#193]
Traceback (most recent call last):
  File "./tagger", line 25, in <module>
    project.tags.create({"tag_name":args.tag,"ref":args.ref,"message":args.message}, sudo=args.user) 
  File "/usr/lib/python2.7/site-packages/gitlab/objects.py", line 142, in create
    return self.obj_cls.create(self.gitlab, data, **args)
  File "/usr/lib/python2.7/site-packages/gitlab/objects.py", line 353, in create
    obj.save()
  File "/usr/lib/python2.7/site-packages/gitlab/objects.py", line 323, in save
    self._create(**kwargs)
  File "/usr/lib/python2.7/site-packages/gitlab/objects.py", line 308, in _create
    json = self.gitlab.create(self, **kwargs)
  File "/usr/lib/python2.7/site-packages/gitlab/__init__.py", line 511, in create
    raise_error_from_response(r, GitlabCreateError, 201)
  File "/usr/lib/python2.7/site-packages/gitlab/exceptions.py", line 180, in raise_error_from_response
    response_body=response.content)
gitlab.exceptions.GitlabCreateError: 403: 403 Forbidden  - Private token must be specified in order to use sudo

**Comment by Delagen** [comment]
No user id or username error for supplied id

**Comment by gpocentek** [comment]
It seems that the error comes from the server, not python-gitlab. Have you disabled token authentication on your server?

Sudo works fine for me with token authentication.

**Comment by Delagen** [comment]
@gpocentek Yes.
1. From version 8.14 Personal Access Tokens was disabled to use sudo. ONLY PRIVATE.
2. When using sudo argument as user id provided as int data type error about `User not found occured`, when supply as string all OK.

**Comment by gpocentek** [comment]
It seems that gitlab now expects a string for the sudo value, even if it's the ID you're using. Could you test this to make sure I'm not wrong?

Thank you.
