### ISSUE TITLE
Cannot get single project by namespace/project-name

### ISSUE THREAD

**Issue by ad-lebedev** [gpocentek/python-gitlab#91]
Hi!
I'm trying to fix problem with sentry-gitlab package, which uses your code.
I found, that I cannot get project by it's name even from python console. But at the same time, I can list all projects, loop over this list and get attributes of each item.
```python
>>> gitlab.__version__
'0.12.1'
```
I'm doing this:
```python
>>> import gitlab
>>> gl = gitlab.Gitlab(*****, ******)
>>> gl.auth()
>>> gl
<gitlab.Gitlab object at 0x7f486102c0d0>
>>> projects = gl.projects.list()
>>> projects[0].id
24
>>> projects[0].path_with_namespace
u'intra/board'
>>> import urllib
>>> gl.projects.get(urllib.quote_plus('intra/board'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/webmaster/.pyenv/versions/sentry-2.7.10/lib/python2.7/site-packages/gitlab/objects.py", line 103, in get
    return self.obj_cls.get(self.gitlab, id, **args)
  File "/home/webmaster/.pyenv/versions/sentry-2.7.10/lib/python2.7/site-packages/gitlab/objects.py", line 282, in get
    return cls(gl, id, **kwargs)
  File "/home/webmaster/.pyenv/versions/sentry-2.7.10/lib/python2.7/site-packages/gitlab/objects.py", line 389, in __init__
    data = self.gitlab.get(self.__class__, data, **kwargs)
  File "/home/webmaster/.pyenv/versions/sentry-2.7.10/lib/python2.7/site-packages/gitlab/__init__.py", line 421, in get
    raise_error_from_response(r, GitlabGetError)
  File "/home/webmaster/.pyenv/versions/sentry-2.7.10/lib/python2.7/site-packages/gitlab/exceptions.py", line 110, in raise_error_from_response
    response_body=response.content)
gitlab.exceptions.GitlabGetError: 404: 404 Project Not Found
```
Do you have any ideas what am I doing wrong?

**Comment by gpocentek** [comment]
I think that the problem comes from the `urllib.quote_plus` call. The conversion of `/` to `%2F` is now done internally. I guess you used a workaround for a problem that's been reported and fixed recently.

**Comment by ad-lebedev** [comment]
Negative.
Without ```urllib```:
```python
>>> import gitlab
>>> gl = gitlab.Gitlab('****************', '******************')
>>> gl.auth()
>>> projects = gl.projects.list()
>>> projects[0]
<gitlab.objects.Project object at 0x7fc5b6bb05d0>
>>> projects[0].name
u'board'
>>> gl.projects.get(projects[0].path_with_namespace)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/webmaster/.pyenv/versions/sentry-2.7.10/lib/python2.7/site-packages/gitlab/objects.py", line 103, in get
    return self.obj_cls.get(self.gitlab, id, **args)
  File "/home/webmaster/.pyenv/versions/sentry-2.7.10/lib/python2.7/site-packages/gitlab/objects.py", line 282, in get
    return cls(gl, id, **kwargs)
  File "/home/webmaster/.pyenv/versions/sentry-2.7.10/lib/python2.7/site-packages/gitlab/objects.py", line 389, in __init__
    data = self.gitlab.get(self.__class__, data, **kwargs)
  File "/home/webmaster/.pyenv/versions/sentry-2.7.10/lib/python2.7/site-packages/gitlab/__init__.py", line 421, in get
    raise_error_from_response(r, GitlabGetError)
  File "/home/webmaster/.pyenv/versions/sentry-2.7.10/lib/python2.7/site-packages/gitlab/exceptions.py", line 110, in raise_error_from_response
    response_body=response.content)
gitlab.exceptions.GitlabGetError: 404: 404 Project Not Found
>>> projects[0].path_with_namespace
u'intra/board'
>>> gl.projects.get('intra/board')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/webmaster/.pyenv/versions/sentry-2.7.10/lib/python2.7/site-packages/gitlab/objects.py", line 103, in get
    return self.obj_cls.get(self.gitlab, id, **args)
  File "/home/webmaster/.pyenv/versions/sentry-2.7.10/lib/python2.7/site-packages/gitlab/objects.py", line 282, in get
    return cls(gl, id, **kwargs)
  File "/home/webmaster/.pyenv/versions/sentry-2.7.10/lib/python2.7/site-packages/gitlab/objects.py", line 389, in __init__
    data = self.gitlab.get(self.__class__, data, **kwargs)
  File "/home/webmaster/.pyenv/versions/sentry-2.7.10/lib/python2.7/site-packages/gitlab/__init__.py", line 421, in get
    raise_error_from_response(r, GitlabGetError)
  File "/home/webmaster/.pyenv/versions/sentry-2.7.10/lib/python2.7/site-packages/gitlab/exceptions.py", line 110, in raise_error_from_response
    response_body=response.content)
gitlab.exceptions.GitlabGetError: 404: 404 Project Not Found
>>> gl.projects.get('intra%2Fboard')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/webmaster/.pyenv/versions/sentry-2.7.10/lib/python2.7/site-packages/gitlab/objects.py", line 103, in get
    return self.obj_cls.get(self.gitlab, id, **args)
  File "/home/webmaster/.pyenv/versions/sentry-2.7.10/lib/python2.7/site-packages/gitlab/objects.py", line 282, in get
    return cls(gl, id, **kwargs)
  File "/home/webmaster/.pyenv/versions/sentry-2.7.10/lib/python2.7/site-packages/gitlab/objects.py", line 389, in __init__
    data = self.gitlab.get(self.__class__, data, **kwargs)
  File "/home/webmaster/.pyenv/versions/sentry-2.7.10/lib/python2.7/site-packages/gitlab/__init__.py", line 421, in get
    raise_error_from_response(r, GitlabGetError)
  File "/home/webmaster/.pyenv/versions/sentry-2.7.10/lib/python2.7/site-packages/gitlab/exceptions.py", line 110, in raise_error_from_response
    response_body=response.content)
gitlab.exceptions.GitlabGetError: 404: 404 Project Not Found
>>>
```

Could you please write an example of accessing the project by name?

**Comment by gpocentek** [comment]
Well your example works fine here:

````` python
>>> import gitlab
>>> gl = gitlab.Gitlab.from_config()
>>> projects = gl.projects.list()
>>> projects[0]
<gitlab.objects.Project object at 0x7f83066be3d0>
>>> projects[0].name
u'infra-openstack'
>>> gl.projects.get(projects[0].path_with_namespace)
<gitlab.objects.Project object at 0x7f8306fa5290>
>>> projects[0].path_with_namespace
u'ol/infra-openstack'
>>> gl.projects.get('ol/infra-openstack')
<gitlab.objects.Project object at 0x7f8306fa5310>
`````

What is your gitlab server version?

**Comment by ad-lebedev** [comment]
7.8.0.rc1, it uses API v3

**Comment by ad-lebedev** [comment]
It was a GitLab server issue, sorry for disturbing you and thank you for your help!

**Comment by gpocentek** [comment]
Happy to read it's working for you.

**Comment by promethe42** [comment]
The problem is probably related to this issue:

https://gitlab.com/gitlab-org/gitlab-ce/issues/35079

**Comment by promethe42** [comment]
Definitely a GitLab/reverse proxy error.

Found the solution. Posted it here:

https://gitlab.com/gitlab-org/gitlab-ce/issues/35079#note_76374269
