### ISSUE TITLE
Exception raised because of u'string' with Python 3.2

### ISSUE THREAD

**Issue by Asher256** [gpocentek/python-gitlab#97]
Hi,

My operating system is Debian Wheezy, with Python 3.2 and the last version of python-gitlab.

The gitlab module raised this exception, because of the 'u' (Unicode):
```
Traceback (most recent call last):
  File "push_settings.py", line 14, in <module>
    from helper import ROOT_EMAIL, ADMINS, git, old_git
  File "/opt/scripts/gitlab/helpers/helper.py", line 25, in <module>
    from gitlab import Gitlab
  File "/opt/scripts/gitlab/helpers/gitlab/__init__.py", line 32, in <module>
    from gitlab.objects import *  # noqa
  File "/opt/scripts/gitlab/helpers/gitlab/objects.py", line 546
    selfdict.pop(u'password', None)
                           ^
SyntaxError: invalid syntax
```

It is a recent change:
01802c0c (Richard Hansen             2016-02-11 22:43:25 -0500  546)             selfdict.pop(u'password', None)
01802c0c (Richard Hansen             2016-02-11 22:43:25 -0500  547)             otherdict.pop(u'password', None)

To solve the issue, 'u' needs to be removed. Could you please fix the little bug?

Thank you Gauvain! Have a nice day.

Best regards,
Asher256

**Comment by Asher256** [comment]
I'm going to send a push request instead.
